version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nest_postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timemanagementsystem
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:18
    container_name: nestjs_app
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: my_nestjs_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: my_nestjs_db
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

volumes:
  postgres_data:
