name: CI Back End

on:
  push:
    branches:
      - main
      - release
      - "release/**" # Add pattern for `release/` branches
  pull_request:
    branches:
      - main
      - release
      - "release/**" # Add pattern for `release/` branches

jobs:
  build:
    if: |
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/heads/release/') || 
      github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install backend dependencies
        working-directory: tms-backend
        run: pnpm install

      - name: Run backend build
        working-directory: tms-backend
        run: pnpm run build

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: tms-backend/build

 test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install backend dependencies
        working-directory: tms-backend
        run: pnpm install

      - name: Ensure coverage directory exists
        working-directory: tms-backend
        run: mkdir -p ./coverage

      - name: Run backend tests
        working-directory: tms-backend
        run: pnpm run test --coverage --reporters=mocha-junit-reporter

      - name: Export test suite and results
        working-directory: tms-backend
        run: |
          mkdir -p ./results
          cp ./test-results/*.xml ./results/

      - name: Commit and push test results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b test-results
          cp ./results/*.xml ./test-results/
          git add ./test-results/*.xml
          git commit -m "Add test results"
          git push origin test-results

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tms-backend/coverage

      - name: Upload test suite results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tms-backend/results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tms-backend/coverage/**/coverage-final.json

      - name: Cache backend pnpm store
        uses: actions/cache@v3
        with:
          path: |
            tms-backend/node_modules/.pnpm-store
            tms-backend/node_modules/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('tms-backend/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  deploy:
    if: startsWith(github.ref, 'refs/heads/release')
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Decode and set up SSH key
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} <<EOF
            curl -fsSL https://get.pnpm.io/install.sh | sh
            export PATH=\$HOME/.local/share/pnpm:$PATH
            cd /home/ec2-user/traning-batch-1-0804/tms-backend
            rm -rf node_modules package-lock.json
            git fetch origin
            git checkout release
            git pull
            pnpm install
            pnpm run build
            pm2 start dist/main.js || pm2 restart dist/main.js
            pm2 startup
            pm2 save
          EOF
 