name: CI Front End

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Delete package-lock.json
        working-directory: tms-frontend
        run: rm -f package-lock.json

      - name: Install frontend dependencies
        working-directory: tms-frontend
        run: pnpm install

      - name: Run frontend build
        working-directory: tms-frontend
        run: pnpm run build

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: tms-frontend/dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Delete package-lock.json
        working-directory: tms-frontend
        run: rm -f package-lock.json

      - name: Install frontend dependencies
        working-directory: tms-frontend
        run: pnpm install

      - name: Ensure coverage directory exists
        working-directory: tms-frontend
        run: mkdir -p ./coverage

      - name: Run frontend tests
        working-directory: tms-frontend
        run: pnpm run test

      - name: Run frontend tests with coverage
        working-directory: tms-frontend
        run: pnpm run test --coverage

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tms-frontend/coverage

      - name: Upload test suite results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: tms-frontend/test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: tms-frontend/test-results/junit.xml
          reporter: jest-junit

      - name: Upload test suite results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tms-frontend/results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tms-frontend/coverage/**/coverage-final.json

      - name: Cache frontend pnpm store
        uses: actions/cache@v3
        with:
          path: |
            tms-frontend/node_modules/.pnpm-store
            tms-frontend/node_modules/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('tms-frontend/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
